# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The Artisan.
tagline:          'The Aesthetics and the craft.'
description:      'Blog about the aesthetics (in metaphorical sense) in the craft. The crafts are pursuits and activities of the author in his daily life.'
url:              http://a8h1nay.github.io

author:
  name:           'Abhinay Thakur'
  url:            http://a8h1nay.github.io

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/a8h1nay/a8h1nay.github.io

excerpt_separator: "<!--excerpt-->"
