# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The Artisan.
tagline:          'The Aesthetics and the craft.'
description:      'Blog about the aesthetic - in metaphoric sense - in the craft. The crafts are pursuits and activities of the author in his daily life.'
url:              http://lanyon.getpoole.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
